# Generated by Django 6.1.1 on 2026-09-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyappStudent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dod', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'myapp_student',
                'managed': False,
            },
        ),
    ]
