# Generated by Django 6.1.1 on 2026-10-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myappstudent',
            name='dod',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='myappstudent',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
