# Generated by Django 6.1.1 on 2026-10-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_myappstudent_dod_myappstudent_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyappStaff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dod', models.DateField(null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=254, unique=True)),
            ],
        ),
    ]
