# Generated by Django 6.1.1 on 2026-10-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_myappstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='myappstaff',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
