# Generated by Django 6.1.1 on 2026-10-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=254)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
