# Generated by Django 6.1.1 on 2026-10-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='user_id',
        ),
    ]
