# Generated by Django 6.1.1 on 2026-10-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_userauth_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userauth',
            table='UserAuth',
        ),
    ]
