# Generated by Django 6.1.1 on 2026-10-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_userauth_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userauth',
            table='myapp_userauth',
        ),
    ]
