# Generated by Django 6.1.1 on 2026-10-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_userauth_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='password',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='userauth',
            table=None,
        ),
    ]
