# Generated by Django 6.1.1 on 2026-10-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_userauth_password_userauth_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
